# -*- coding: utf-8 -*-
"""Copy of Play-Watch-Pass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4jWUKWMS7XCbHLoBgsFnC67zBscO6NK
"""

# ============================================================
# KMQuant Story Dashboard (HTML) — UPPER LEVEL (v2.1 CLEAN)
# Fixes:
#   - No SettingWithCopyWarning (copy() + .loc assignments)
#   - Robust GoldenScore_MDL percentile threshold
# Features:
#   - CONFLICT detection
#   - Market RELIABILITY
#   - DEMO Headline
# Output:
#   - dashboard.html (offline)
# ============================================================

import pandas as pd
import numpy as np
import json
from google.colab import files

# ----------------------------
# 0) Upload
# ----------------------------
uploaded = files.upload()
path = next(iter(uploaded.keys()))
df = pd.read_csv(path)

# ----------------------------
# 1) Normalize / types
# ----------------------------
num_cols = [
    "Odd","Prob","EV",
    "EFFECTIVE_N","_EN_PEN",
    "SIM_ANCHOR_STRENGTH","MDL_rank","MDL_quantile",
    "BestOfRank","Star_Rating","MDL_BOOST","GoldenScore_MDL"
]
for c in num_cols:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce")

str_cols = ["TRAP_ICON","DANGER_ICON","CONF_ICON","AUTOMOD_ICON","STRENGTH_ICON","ARCH_ICON","AnchorStrengthCategory","Market"]
for c in str_cols:
    if c in df.columns:
        df[c] = df[c].fillna("").astype(str)

required_min = ["Match_ID","Seçim","Karakter"]
missing_min = [c for c in required_min if c not in df.columns]
if missing_min:
    raise ValueError(f"Eksik minimum kolonlar: {missing_min}\nMevcut: {list(df.columns)}")

def infer_from_match_id(mid: str):
    parts = str(mid).split("|")
    if len(parts) >= 4:
        return parts[0], parts[1], parts[2], parts[3]
    return "", "", "", ""

if "League" not in df.columns or "HomeTeam" not in df.columns or "AwayTeam" not in df.columns:
    inferred = df["Match_ID"].apply(infer_from_match_id)
    if "Date" not in df.columns: df["Date"] = [t[0] for t in inferred]
    if "League" not in df.columns: df["League"] = [t[1] for t in inferred]
    if "HomeTeam" not in df.columns: df["HomeTeam"] = [t[2] for t in inferred]
    if "AwayTeam" not in df.columns: df["AwayTeam"] = [t[3] for t in inferred]
else:
    if "Date" not in df.columns:
        df["Date"] = df["Match_ID"].apply(lambda x: infer_from_match_id(x)[0])

for c in ["Odd","Prob","EV","EFFECTIVE_N"]:
    if c not in df.columns:
        df[c] = np.nan

def is_blank(x):
    s = str(x).strip()
    return s == "" or s.lower() == "nan"

def safe_row(r):
    return is_blank(r.get("TRAP_ICON","")) and is_blank(r.get("DANGER_ICON",""))

df["_SAFE"] = df.apply(safe_row, axis=1)

def get_col(sub, name):
    return sub[name] if name in sub.columns else None

def ratio_green(series, green="🟢"):
    if series is None:
        return np.nan
    s = series.astype(str)
    return float((s == green).sum()) / max(1, len(s))

def med(series):
    if series is None:
        return np.nan
    return float(np.nanmedian(pd.to_numeric(series, errors="coerce").values))

def any_nonblank(series):
    if series is None:
        return False
    return series.astype(str).str.strip().ne("").any()

# ----------------------------
# 2) Structures
# ----------------------------
TRIANGLES = {
    "MS1 + 2.5Üst + KGVar": {"MS 1", "2.5 Üst", "KG Var"},
    "MS2 + 2.5Üst + KGVar": {"MS 2", "2.5 Üst", "KG Var"},
    "MS1 + 2.5Alt + KGVar": {"MS 1", "2.5 Alt", "KG Var"},
    "MS2 + 2.5Alt + KGVar": {"MS 2", "2.5 Alt", "KG Var"},
    "MS1 + 3.5Üst + KGVar": {"MS 1", "3.5 Üst", "KG Var"},
    "MS2 + 3.5Üst + KGVar": {"MS 2", "3.5 Üst", "KG Var"},
}
BANKO_MARKETS = {"MS 1","MS 2","MS X"}
GOAL_MARKETS  = {"2.5 Üst","2.5 Alt","3.5 Üst","3.5 Alt"}
VALUE_GATES   = {"KG Var","KG Yok"}

markets_per_match = df.groupby("Match_ID")["Seçim"].apply(lambda s: set(map(str, s))).to_dict()
ev_max_map = (df.groupby(["Match_ID","Seçim"])["EV"].max()).to_dict()

bor_max_map = (df.groupby(["Match_ID","Seçim"])["BestOfRank"].max()).to_dict() if "BestOfRank" in df.columns else {}

gs_med_map = df.groupby("Match_ID")["GoldenScore_MDL"].median().to_dict() if "GoldenScore_MDL" in df.columns else {}
boost_med_map = df.groupby("Match_ID")["MDL_BOOST"].median().to_dict() if "MDL_BOOST" in df.columns else {}

# Robust percentile threshold for GoldenScore_MDL
GS_THR_75 = np.nan
if gs_med_map:
    gs_vals = np.array([v for v in gs_med_map.values() if np.isfinite(v)], dtype=float)
    if len(gs_vals):
        GS_THR_75 = float(np.nanpercentile(gs_vals, 75))

def detect_triangles(mid):
    mset = markets_per_match.get(mid, set())
    hits = []
    for name, req in TRIANGLES.items():
        if req.issubset(mset):
            hits.append(name)
    return hits

def triangle_price_killed(mid, triangles_exist):
    if not triangles_exist:
        return (False, "", "")

    banko_evs = [ev_max_map.get((mid,m), np.nan) for m in BANKO_MARKETS]
    goal_evs  = [ev_max_map.get((mid,m), np.nan) for m in GOAL_MARKETS]
    val_evs   = [(m, ev_max_map.get((mid,m), np.nan)) for m in VALUE_GATES]

    banko_evs = [float(x) for x in banko_evs if np.isfinite(x)]
    goal_evs  = [float(x) for x in goal_evs if np.isfinite(x)]
    val_evs   = [(m,float(v)) for (m,v) in val_evs if np.isfinite(v)]

    banko_killed = (len(banko_evs)>0) and (max(banko_evs) <= 0)
    goal_killed  = (len(goal_evs)>0)  and (max(goal_evs)  <= 0)
    value_gate   = (len(val_evs)>0) and (max([v for _,v in val_evs]) > 0)

    killed = (banko_killed or goal_killed) and value_gate
    gate = ""
    if killed:
        gate = sorted(val_evs, key=lambda t: t[1], reverse=True)[0][0]

    detail = []
    if banko_killed: detail.append("Banko tarafı fiyatlanmış")
    if goal_killed:  detail.append("Gol marketi fiyatlanmış")
    return killed, gate, " + ".join(detail)

# ----------------------------
# 3) CONFLICT (upper)
# ----------------------------
CONFLICT_PAIRS = [
    ("KG Var", "KG Yok", "BTTS conflict"),
    ("2.5 Üst", "2.5 Alt", "OU 2.5 conflict"),
    ("3.5 Üst", "3.5 Alt", "OU 3.5 conflict"),
    ("MS 1", "MS 2", "1X2 conflict"),
    ("MS 1", "MS X", "1X2 conflict"),
    ("MS X", "MS 2", "1X2 conflict"),
]

def conflict_tag(mid):
    conflicts = []
    for a, b, label in CONFLICT_PAIRS:
        eva = ev_max_map.get((mid,a), np.nan)
        evb = ev_max_map.get((mid,b), np.nan)
        bora = bor_max_map.get((mid,a), np.nan) if bor_max_map else np.nan
        borb = bor_max_map.get((mid,b), np.nan) if bor_max_map else np.nan

        if np.isfinite(eva) and np.isfinite(evb) and (eva > 0) and (evb > 0):
            conflicts.append(f"{label}: {a} vs {b}")
            continue

        if np.isfinite(bora) and np.isfinite(borb) and (bora >= 1.05) and (borb >= 1.05):
            conflicts.append(f"{label}(BoR): {a} vs {b}")

    if not conflicts:
        return "CONFLICT: NONE", ""
    return "CONFLICT: YES", " | ".join(conflicts[:3])

# ----------------------------
# 4) RELIABILITY (upper, clean)
# ----------------------------
def market_reliability(sub, mid):
    """
    Reliability uses:
    - support: positive EV rows + unique chars among those
    - BestOfRank strength for best market
    - match-level GoldenScore_MDL / MDL_BOOST
    """
    s = sub.copy()
    s.loc[:, "EVn"] = pd.to_numeric(s["EV"], errors="coerce")

    pos = s.loc[s["EVn"] > 0].copy()   # ✅ copy => no warning

    pos_rows = int(len(pos))
    pos_chars = int(pos["Karakter"].nunique()) if pos_rows else 0

    if pos_rows:
        pos.loc[:, "_p"] = pd.to_numeric(pos.get("Prob", np.nan), errors="coerce").fillna(0)
        pos = pos.sort_values(["EVn","_p"], ascending=False)
        best_market = str(pos.iloc[0]["Seçim"])
    else:
        if "BestOfRank" in s.columns:
            s2 = s.copy()
            s2.loc[:, "_bor"] = pd.to_numeric(s2["BestOfRank"], errors="coerce").fillna(-1e9)
            best_market = str(s2.sort_values("_bor", ascending=False).iloc[0]["Seçim"])
        else:
            best_market = str(s.iloc[0]["Seçim"])

    bor = bor_max_map.get((mid,best_market), np.nan) if bor_max_map else np.nan
    gs = gs_med_map.get(mid, np.nan) if gs_med_map else np.nan
    boost = boost_med_map.get(mid, np.nan) if boost_med_map else np.nan

    score = 0

    # support
    if pos_rows >= 3: score += 2
    elif pos_rows == 2: score += 1
    if pos_chars >= 2: score += 2
    elif pos_chars == 1 and pos_rows >= 2: score += 1

    # BestOfRank
    if np.isfinite(bor):
        if bor >= 1.15: score += 2
        elif bor >= 1.05: score += 1

    # MDL strength (robust threshold)
    if np.isfinite(GS_THR_75) and np.isfinite(gs) and gs >= GS_THR_75:
        score += 1

    # boost positive support
    if np.isfinite(boost) and boost > 0:
        score += 1

    if score >= 5:
        return "RELIABILITY: HIGH", best_market
    if score >= 3:
        return "RELIABILITY: MED", best_market
    return "RELIABILITY: LOW", best_market

# ----------------------------
# 5) Base tags
# ----------------------------
def core_tag(sub):
    mdl_rank = med(get_col(sub, "MDL_rank"))
    q = med(get_col(sub, "MDL_quantile"))
    cr = ratio_green(get_col(sub, "CONF_ICON"))
    ar = ratio_green(get_col(sub, "AUTOMOD_ICON"))

    if np.isfinite(mdl_rank) and mdl_rank <= 1 and np.isfinite(q) and q >= 0.75 and cr >= 0.70:
        return "CORE: STRONG" if ar >= 0.40 else "CORE: STRONG-ish"
    if cr >= 0.60 and (np.isfinite(q) and q >= 0.60):
        return "CORE: OK"
    return "CORE: FRAGILE"

def sample_tag(sub):
    eff = med(get_col(sub, "EFFECTIVE_N"))
    pen = med(get_col(sub, "_EN_PEN"))
    if not np.isfinite(pen):
        pen = 0.0

    if np.isfinite(eff) and eff >= 40:
        return "SAMPLE: THICK (PEN)" if pen >= 3 else "SAMPLE: THICK"
    if np.isfinite(eff) and eff >= 30:
        return "SAMPLE: OK (PEN)" if pen >= 3 else "SAMPLE: OK"
    if np.isfinite(eff) and eff >= 20:
        return "SAMPLE: THIN"
    return "SAMPLE: VERY THIN"

def edge_tag(sub):
    s = sub.copy()
    s.loc[:, "EVn"] = pd.to_numeric(s["EV"], errors="coerce")
    pos = s.loc[s["EVn"] > 0]
    if len(pos) == 0:
        return "EDGE: NONE"
    pos_rows = int(len(pos))
    pos_chars = int(pos["Karakter"].nunique())
    if pos_rows >= 3 and pos_chars >= 2:
        return "EDGE: ROBUST"
    if pos_rows >= 2:
        return "EDGE: OK"
    return "EDGE: FRAGILE"

def consistency_tag(sub):
    sicon = get_col(sub, "STRENGTH_ICON")
    scat = get_col(sub, "AnchorStrengthCategory")
    drift = False
    if sicon is not None and sicon.astype(str).str.strip().nunique() >= 2:
        drift = True
    if scat is not None and scat.astype(str).str.strip().nunique() >= 2:
        drift = True
    return "CONSISTENCY: DRIFT" if drift else "CONSISTENCY: CLEAN"

def arch_tag(sub):
    arch = get_col(sub, "ARCH_ICON")
    if arch is None:
        return "ARCH: N/A"
    uniq = arch.astype(str).str.strip()
    uniq = uniq[uniq != ""]
    if len(uniq) == 0:
        return "ARCH: N/A"
    n = uniq.nunique()
    if n == 1: return "ARCH: FOCUSED"
    if n == 2: return "ARCH: MIXED"
    return "ARCH: NOISY"

def story_tag(sub, triangles):
    rows = len(sub)
    um = sub["Seçim"].nunique()
    uc = sub["Karakter"].nunique()
    if len(triangles) > 0 and rows >= 6 and um >= 3 and uc >= 2:
        return "STORY: HIGH (TRI)"
    if rows >= 6 and um >= 3 and uc >= 2:
        return "STORY: HIGH"
    if rows >= 4 and um >= 2:
        return "STORY: MED"
    return "STORY: LOW"


# ----------------------------
# 5b) Smart WATCH split helpers
# ----------------------------
def story_density(sub):
    rows = int(len(sub))
    um = int(sub["Seçim"].nunique())
    uc = int(sub["Karakter"].nunique())
    if rows >= 6 and um >= 3 and uc >= 2:
        return "DENSITY: HIGH"
    if rows >= 4 and um >= 2:
        return "DENSITY: MED"
    return "DENSITY: LOW"

def market_dominance(sub):
    mset = set(map(str, sub["Seçim"].unique()))
    has_ms = any(m.startswith("MS") for m in mset)
    has_goal = any(m in GOAL_MARKETS or m in VALUE_GATES for m in mset)
    if has_ms and has_goal:
        return "DOM: RESULT+GOAL"
    if has_ms:
        return "DOM: RESULT"
    if has_goal:
        return "DOM: GOAL"
    return "DOM: MIXED"

def conf_alignment(sub):
    conf = get_col(sub, "CONF_ICON")
    am = get_col(sub, "AUTOMOD_ICON")
    conf_g = int((conf=="🟢").sum()) if conf is not None else 0
    am_g = int((am=="🟢").sum()) if am is not None else 0
    if conf_g >= 2 and am_g >= 1:
        return "ALIGN: SYNC"
    if conf_g >= 1:
        return "ALIGN: PARTIAL"
    return "ALIGN: WEAK"

def price_status(mid, pk, gate):
    # pk => triangle_price_killed (banko killed but value gate open)
    if pk and gate:
        return "PRICE_STATUS: BANKO_KILLED_VALUE_OPEN"
    evs = [ev_max_map.get((mid,m), np.nan) for m in markets_per_match.get(mid,set())]
    evs = [float(x) for x in evs if np.isfinite(x)]
    if evs and max(evs) <= 0:
        return "PRICE_STATUS: PRICED_IN"
    return "PRICE_STATUS: OPEN"

def mini_commentary(sub, mid, tags, triangles, pk, gate):
    # 2–3 cümle, yorumcu modu (rakam yok)
    dom = tags.get("MARKET_DOM","")
    dens = tags.get("DENSITY","")
    align = tags.get("ALIGN","")
    price = tags.get("PRICE_STATUS","")

    # best market heuristic
    best = tags.get("RELIABILITY_BEST_MARKET","")
    base = []
    if triangles:
        base.append(f"Bu maç üçgen kuruyor: {triangles[0]}. ")
    else:
        if dom == "DOM: RESULT+GOAL":
            base.append("Bu maçta hem sonuç hem gol tarafı konuşuyor. ")
        elif dom == "DOM: RESULT":
            base.append("Hikâye daha çok sonuç tarafında dönüyor. ")
        elif dom == "DOM: GOAL":
            base.append("Hikâye gol/tempo ekseninde dönüyor. ")
        else:
            base.append("Sinyal var ama eksen net değil. ")

    if dens == "DENSITY: HIGH":
        base.append("Yoğunluk yüksek; model tek bir fikre akmaya yakın. ")
    elif dens == "DENSITY: MED":
        base.append("Yoğunluk orta; teyit arıyor. ")
    else:
        base.append("Yoğunluk düşük; gürültü riski var. ")

    if price == "PRICE_STATUS: BANKO_KILLED_VALUE_OPEN":
        base.append(f"Piyasa banko kapısını kapatmış ama value kapısı açık ({gate}). ")
    elif price == "PRICE_STATUS: PRICED_IN":
        base.append("Fiyat tarafı kapalı; izlemek daha sağlıklı. ")
    else:
        base.append("Fiyat tarafında çalışılabilir bir kapı var. ")

    if align == "ALIGN: SYNC":
        base.append("CONF ve AutoMod aynı yeri işaret ediyor. ")
    elif align == "ALIGN: PARTIAL":
        base.append("CONF var ama senkron tam değil. ")
    else:
        base.append("CONF/AutoMod dağılıyor; acele etmem. ")

    if best:
        base.append(f"En makul okuma: {best}.")
    return "".join(base).strip()

def price_tag(mid, triangles_exist, price_killed, gate):
    if triangles_exist and price_killed and gate:
        return f"PRICE: KILLED → {gate}"
    evs = [ev_max_map.get((mid,m), np.nan) for m in markets_per_match.get(mid,set())]
    evs = [float(x) for x in evs if np.isfinite(x)]
    if evs and max(evs) <= 0:
        return "PRICE: PRICED-IN"
    return "PRICE: OPEN"

# ----------------------------
# 6) Verdict + pick selection (clean)
# ----------------------------
def verdict(sub, tags, pk):
    trap = any_nonblank(get_col(sub, "TRAP_ICON")) or any_nonblank(get_col(sub, "DANGER_ICON"))
    cr = ratio_green(get_col(sub, "CONF_ICON"))

    if trap:
        return "PASS", "Tuzak/tehlike etiketi var: burada ‘hikâye’ değil ‘risk’ baskın."

    if tags["CONFLICT_TAG"] == "CONFLICT: YES":
        if tags["EDGE_TAG"] in ("EDGE: NONE","EDGE: FRAGILE"):
            return "PASS", "Konflikt var ve edge zayıf; burada yön seçmek kumara döner."
        return "WATCH", "Konflikt var; tek bir hikâyeye kilitlenmeden izlemek daha doğru."

    if tags["EDGE_TAG"] == "EDGE: NONE":
        if tags["CORE_TAG"].startswith("CORE: STRONG"):
            return "WATCH", "Model seviyor ama fiyat kapalı. Zorlamam; izlerim."
        return "WATCH", "Hikâye var gibi ama fiyat kapısı yok."

    if cr < 0.55:
        return "PASS", "CONF dağınık; model aynı şeyi anlatmıyor."

    if tags["RELIABILITY_TAG"] == "RELIABILITY: HIGH" and tags["EDGE_TAG"] in ("EDGE: ROBUST","EDGE: OK") and tags["SAMPLE_TAG"].startswith("SAMPLE: THICK"):
        if pk:
            return "PLAY", "Hikâye güçlü; banko tarafı fiyatlanmış. Value gate’e kaymak mantıklı."
        return "PLAY", "Çekirdek + edge + reliability aynı anda geliyor; oynanabilir."

    if tags["RELIABILITY_TAG"] == "RELIABILITY: MED" and tags["CORE_TAG"].startswith("CORE: STRONG"):
        return "WATCH", "Sinyal var; ama tam ‘konfor’ için reliability bir tık daha isterim."

    return "WATCH", "Sinyal var ama ‘tam konfor’ değil; dalga payıyla izlenebilir."

def best_pick_row(sub):
    s = sub.loc[sub["_SAFE"]==True].copy()  # ✅ copy => no warning
    if len(s) == 0:
        s = sub.copy()

    if "CONF_ICON" in s.columns:
        s.loc[:, "_conf"] = (s["CONF_ICON"]=="🟢").astype(int)
    else:
        s.loc[:, "_conf"] = 0

    if "AUTOMOD_ICON" in s.columns:
        s.loc[:, "_am"] = (s["AUTOMOD_ICON"]=="🟢").astype(int)
    else:
        s.loc[:, "_am"] = 0

    s.loc[:, "_ev"]  = pd.to_numeric(s["EV"], errors="coerce").fillna(-1e9)
    s.loc[:, "_p"]   = pd.to_numeric(s["Prob"], errors="coerce").fillna(0)

    if "BestOfRank" in s.columns:
        s.loc[:, "_bor"] = pd.to_numeric(s["BestOfRank"], errors="coerce").fillna(0)
    else:
        s.loc[:, "_bor"] = 0

    s = s.sort_values(["_conf","_am","_ev","_bor","_p"], ascending=False)
    return s.iloc[0]

# ----------------------------
# 7) DEMO headline + narrative
# ----------------------------
def headline(tags, triangles, pk, gate):
    if tags["CONFLICT_TAG"] == "CONFLICT: YES":
        return f"⚠️ Konflikt: {tags.get('CONFLICT_DETAIL') or 'iki hikâye aynı anda çekiyor.'}"
    if triangles and pk and gate:
        return f"💀 Banko hissi var ama fiyat öldü → value kapısı: {gate}"
    if triangles:
        return f"🧩 Hikâye üçgeni: {triangles[0]}"
    if tags["EDGE_TAG"] == "EDGE: ROBUST" and tags["RELIABILITY_TAG"] == "RELIABILITY: HIGH":
        return "✅ Edge sağlam ve doğrulanmış: hikâye tek bir fikre akıyor."
    if tags["EDGE_TAG"] == "EDGE: FRAGILE":
        return "🎯 Fikir var ama tek satır riski: ‘şanslı satır’ olabilir."
    if tags["PRICE_TAG"].startswith("PRICE: PRICED-IN"):
        return "🧱 Model seviyor ama fiyat kapalı: izlenir, zorlanmaz."
    return "🕵️ Hikâye var; karar fiyatın izin verdiği kapıda."

def demo_narrative(sub, triangles, pk, gate, tags):
    mset = set(map(str, sub["Seçim"].unique()))
    eff = med(get_col(sub, "EFFECTIVE_N"))
    conf = get_col(sub, "CONF_ICON")
    am = get_col(sub, "AUTOMOD_ICON")
    conf_g = int((conf=="🟢").sum()) if conf is not None else 0
    am_g = int((am=="🟢").sum()) if am is not None else 0
    total = int(len(sub))

    if tags["CONFLICT_TAG"] == "CONFLICT: YES":
        opening = "Bu maçta model aynı anda iki farklı kapıyı açmaya çalışıyor. Bu iyi bir ‘hikâye’ değil; bu bir **çekişme**."
        conflict = f"Konflikt: {tags.get('CONFLICT_DETAIL') or '—'}."
        price_line = "Böyle maçlarda tek hamle değil, ya **pas** ya da net bir ‘gate’ aramak gerekir."
        close = f"CONF 🟢 ({conf_g}/{total}), AutoMod 🟢 ({am_g}/{total}), EffN ~ {eff:.1f}."
        return " ".join([opening, conflict, price_line, close])

    if triangles:
        opening = f"Bu maç **{triangles[0]}** şeklinde net bir *hikâye üçgeni* kuruyor."
    else:
        if ("MS 1" in mset or "MS 2" in mset) and (("2.5 Üst" in mset) or ("2.5 Alt" in mset) or ("KG Var" in mset) or ("KG Yok" in mset)):
            opening = "Maç tek eksenli değil: **sonuç** tarafı da konuşuyor, **gol** tarafı da."
        elif ("KG Var" in mset or "KG Yok" in mset):
            opening = "Hikâye gol temasında dönüyor: 'iki taraf skora dokunur mu?'"
        else:
            opening = "Model bu maçın etrafında yoğun sinyal üretmiş; ‘burada bir şey var’ hissi oluşmuş."

    if pk and gate:
        price_line = f"Banko hissi var ama piyasa o kapıyı kapatmış. Bu maçta **value kapısı**: **{gate}**."
    else:
        if tags["EDGE_TAG"] == "EDGE: NONE":
            price_line = "Hikâye var gibi ama fiyat kapalı; zorlamam."
        elif tags["RELIABILITY_TAG"] == "RELIABILITY: HIGH":
            price_line = "Edge sadece var değil; aynı zamanda **doğrulanmış**. Bu önemli."
        elif tags["EDGE_TAG"] == "EDGE: FRAGILE":
            price_line = "Edge tek bir yerden aralanmış gibi; burada ‘şanslı satır’ riskine dikkat."
        else:
            price_line = "Fiyat tarafında çalışılabilir bir kapı var; mesele doğru fikri doğru fiyata bağlamak."

    cons = "Etiket/strength tarafında **drift** var; anlatı güçlü olsa bile ‘etiket gürültüsü’ taşıyor." if tags["CONSISTENCY_TAG"]=="CONSISTENCY: DRIFT" else "Etiket tarafı temiz; maç ‘dağılmıyor’."
    close = f"CONF 🟢 ({conf_g}/{total}), AutoMod 🟢 ({am_g}/{total}), EffN ~ {eff:.1f}."
    return " ".join([opening, price_line, cons, close])

def explain_block(tags, verdict_text, triangles, pk, gate):
    t = triangles[0] if triangles else "—"
    pk_line = f"Evet (Gate: {gate})" if pk and gate else ("Evet" if pk else "Hayır")
    cd = tags.get("CONFLICT_DETAIL") or "—"
    lines = [
        f"• Headline: {tags.get('HEADLINE','—')}",
        f"• Çekirdek: {tags['CORE_TAG']}",
        f"• Örneklem: {tags['SAMPLE_TAG']}",
        f"• Edge: {tags['EDGE_TAG']}",
        f"• Reliability: {tags['RELIABILITY_TAG']} (best market: {tags.get('RELIABILITY_BEST_MARKET','—')})",
        f"• Tutarlılık: {tags['CONSISTENCY_TAG']}",
        f"• Arketip: {tags['ARCH_TAG']}",
        f"• Konflikt: {tags['CONFLICT_TAG']} ({cd})",
        f"• Hikâye: {tags['STORY_TAG']} (Üçgen: {t})",
        f"• Fiyat: {tags['PRICE_TAG']} (Fiyat öldü: {pk_line})",
        f"• Karar: {verdict_text}"
    ]
    return "<br/>".join(lines)

# ----------------------------
# 8) Build cards
# ----------------------------
cards = []
for mid, sub in df.groupby("Match_ID"):
    triangles = detect_triangles(mid)
    pk, gate, pk_detail = triangle_price_killed(mid, len(triangles)>0)

    tags = {}
    tags["CORE_TAG"] = core_tag(sub)
    tags["SAMPLE_TAG"] = sample_tag(sub)
    tags["EDGE_TAG"] = edge_tag(sub)
    tags["CONSISTENCY_TAG"] = consistency_tag(sub)
    tags["ARCH_TAG"] = arch_tag(sub)
    tags["STORY_TAG"] = story_tag(sub, triangles)
    tags["PRICE_TAG"] = price_tag(mid, len(triangles)>0, pk, gate)

    ctag, cdetail = conflict_tag(mid)
    tags["CONFLICT_TAG"] = ctag
    tags["CONFLICT_DETAIL"] = cdetail

    rtag, best_mkt = market_reliability(sub, mid)
    tags["RELIABILITY_TAG"] = rtag
    tags["RELIABILITY_BEST_MARKET"] = best_mkt

    v, v_reason = verdict(sub, tags, pk)

    # ----------------------------
    # 6b) Smart WATCH split + Hidden Play
    # ----------------------------
    tags["DENSITY"] = story_density(sub)
    tags["MARKET_DOM"] = market_dominance(sub)
    tags["ALIGN"] = conf_alignment(sub)
    tags["PRICE_STATUS"] = price_status(mid, pk, gate)

    # WATCH → WATCH-A/B/C
    if v == "WATCH":
        if tags["DENSITY"] == "DENSITY: HIGH" and tags["ALIGN"] in ("ALIGN: SYNC","ALIGN: PARTIAL") and tags["PRICE_STATUS"] in ("PRICE_STATUS: OPEN","PRICE_STATUS: BANKO_KILLED_VALUE_OPEN"):
            v, v_reason = "WATCH-A", "Hikâye net, fiyat izin veriyor. Karar eşiğinde."
        elif tags["DENSITY"] == "DENSITY: MED" and tags["ALIGN"] != "ALIGN: WEAK":
            v, v_reason = "WATCH-B", "Sinyal var ama teyit ister."
        else:
            v, v_reason = "WATCH-C", "Gürültü baskın. Zaman ayırmaya değmez."

    # Hidden Play (yorumcu oyunu)
    if v in ("WATCH","WATCH-A"):
        if tags["DENSITY"] == "DENSITY: HIGH" and tags["PRICE_STATUS"] == "PRICE_STATUS: BANKO_KILLED_VALUE_OPEN" and tags["ALIGN"] == "ALIGN: SYNC":
            v, v_reason = "HIDDEN PLAY", "Banko fiyatlanmış ama value kapısı açık. Yorumcu oyunu."

    tags["MINI_COMMENT"] = mini_commentary(sub, mid, tags, triangles, pk, gate)


    best = best_pick_row(sub)
    pick = {
        "market": str(best.get("Seçim","")),
        "odd": float(best["Odd"]) if np.isfinite(best.get("Odd",np.nan)) else None,
        "prob": float(best["Prob"]) if np.isfinite(best.get("Prob",np.nan)) else None,
        "ev": float(best["EV"]) if np.isfinite(best.get("EV",np.nan)) else None,
        "profile": str(best.get("Karakter","")),
        "conf": str(best.get("CONF_ICON","")),
        "am": str(best.get("AUTOMOD_ICON","")),
    }

    league = str(sub["League"].iloc[0])
    home = str(sub["HomeTeam"].iloc[0])
    away = str(sub["AwayTeam"].iloc[0])

    head = headline(tags, triangles, pk, gate)
    tags["HEADLINE"] = head

    card = {
        "match_id": str(mid),
        "league": league,
        "home": home,
        "away": away,
        "rows": int(len(sub)),
        "unique_markets": int(sub["Seçim"].nunique()),
        "unique_characters": int(sub["Karakter"].nunique()),
        "has_triangle": bool(len(triangles)>0),
        "triangle_types": ", ".join(triangles),
        "triangle_price_killed": bool(pk),
        "value_gate": gate,
        "killed_detail": pk_detail,
        "verdict": v,
        "reason": v_reason,
        "headline": head,
        "tags": tags,
        "narrative": demo_narrative(sub, triangles, pk, gate, tags),
        "mini_comment": tags.get("MINI_COMMENT",""),
        "explain_html": explain_block(tags, v_reason, triangles, pk, gate),
        "pick": pick,
    }
    cards.append(card)

order = {"PLAY":0, "HIDDEN PLAY":1, "WATCH-A":2, "WATCH-B":3, "WATCH-C":4, "WATCH":5, "PASS":6}
rel_order = {"RELIABILITY: HIGH":0, "RELIABILITY: MED":1, "RELIABILITY: LOW":2}
cards = sorted(cards, key=lambda c: (
    order.get(c["verdict"],9),
    int(c["tags"]["CONFLICT_TAG"]=="CONFLICT: YES"),
    -int(c["triangle_price_killed"]),
    rel_order.get(c["tags"]["RELIABILITY_TAG"],9),
    -c["rows"],
    -c["unique_characters"],
))

data_json = json.dumps(cards, ensure_ascii=False)

# ----------------------------
# 9) HTML dashboard
# ----------------------------
html = f"""<!doctype html>
<html lang="tr">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>KMQuant Story Dashboard (Upper Clean)</title>
<style>
  :root {{
    --bg:#0b0f17; --panel:#121a26; --panel2:#0f1520; --text:#e6e9ef;
    --muted:#9aa4b2; --border:#233047;
    --good:#2ecc71; --warn:#f1c40f; --bad:#e74c3c;
    --chip:#1b2638; --chip2:#0e1623;
  }}
  body{{margin:0;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial;}}
  header{{position:sticky;top:0;background:rgba(11,15,23,.92);backdrop-filter: blur(8px);border-bottom:1px solid var(--border);z-index:10;}}
  .wrap{{max-width:1200px;margin:0 auto;padding:16px;}}
  h1{{font-size:20px;margin:0 0 8px 0;}}
  .sub{{color:var(--muted);font-size:13px;margin:0 0 12px 0;}}
  .controls{{display:grid;grid-template-columns: 1fr 180px 180px 180px; gap:10px; align-items:center;}}
  input, select{{background:var(--panel);border:1px solid var(--border);color:var(--text);padding:10px;border-radius:10px;font-size:14px;outline:none;}}
  .row2{{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-top:10px;flex-wrap:wrap;}}
  .toggle{{display:flex;gap:8px;align-items:center;background:var(--panel2);border:1px solid var(--border);border-radius:999px;padding:8px 12px;}}
  .toggle input{{transform:scale(1.2);}}
  .kpis{{display:flex;gap:10px;flex-wrap:wrap;}}
  .kpi{{background:var(--panel2);border:1px solid var(--border);border-radius:14px;padding:10px 12px;}}
  .kpi b{{font-size:16px;}}
  .grid{{display:grid;grid-template-columns: repeat(2, 1fr); gap:12px; margin-top:14px;}}
  @media (max-width: 980px){{.grid{{grid-template-columns:1fr;}} .controls{{grid-template-columns:1fr 1fr;}}}}
  .card{{background:var(--panel);border:1px solid var(--border);border-radius:18px;padding:14px;}}
  .topline{{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;}}
  .title{{font-size:16px;font-weight:800;line-height:1.2;}}
  .headline{{margin-top:6px;font-size:13px;line-height:1.35;color:var(--text);}}
  .league{{color:var(--muted);font-size:12px;margin-top:6px;}}
  .badge{{padding:6px 10px;border-radius:999px;font-weight:800;font-size:12px; border:1px solid var(--border); background:var(--chip2);}}
  .PLAY{{color:var(--good);}}
  .WATCH{{color:var(--warn);}}
  .PASS{{color:var(--bad);}}
  .chips{{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px;}}
  .chip{{background:var(--chip);border:1px solid var(--border);border-radius:999px;padding:6px 10px;font-size:12px;color:var(--text);}}
  .chip small{{color:var(--muted);}}
  .narr{{margin-top:10px;color:var(--text);font-size:13px;line-height:1.55;}}
  .reason{{margin-top:10px;color:var(--muted);font-size:12px;}}
  details{{margin-top:10px;border-top:1px solid var(--border);padding-top:10px;}}
  summary{{cursor:pointer;color:var(--muted);font-size:12px;}}
  .pickbox{{margin-top:10px;background:var(--panel2);border:1px solid var(--border);border-radius:14px;padding:10px;}}
  .pickline{{display:flex;justify-content:space-between;gap:10px;align-items:center;}}
  .pickline b{{font-size:13px;}}
  .nums{{color:var(--muted);font-size:12px;}}
  .muted{{color:var(--muted);}}
  .explain{{margin-top:10px;color:var(--text);font-size:12px;line-height:1.55;}}
</style>
</head>
<body>
<header>
  <div class="wrap">
    <h1>KMQuant Story Dashboard (Upper · Clean)</h1>
    <p class="sub">Konflikt + Reliability + Headline. Warning yok. “Rakam değil çıkarım” modu.</p>

    <div class="controls">
      <input id="q" placeholder="Ara: takım, lig, market, tag (örn: CONFLICT, RELIABILITY, PRICE, KG Var)"/>
      <select id="verdict">
        <option value="ALL">Tümü</option>
        <option value="PLAY">PLAY</option>
        <option value="HIDDEN PLAY">HIDDEN PLAY</option>
        <option value="WATCH-A">WATCH-A</option>
        <option value="WATCH-B">WATCH-B</option>
        <option value="WATCH-C">WATCH-C</option>
        <option value="WATCH">WATCH</option>
        <option value="PASS">PASS</option>
      </select>
      <select id="triangle">
        <option value="ALL">Üçgen: Tümü</option>
        <option value="YES">Üçgen Var</option>
        <option value="NO">Üçgen Yok</option>
      </select>
      <select id="pricekilled">
        <option value="ALL">Fiyat: Tümü</option>
        <option value="YES">Fiyat Öldü (Value Gate)</option>
        <option value="NO">Normal</option>
      </select>
    </div>

    <div class="row2">
      <div class="kpis" id="kpis"></div>
      <label class="toggle">
        <input id="showNums" type="checkbox"/>
        <span class="muted">Rakamları göster (Odd/Prob/EV)</span>
      </label>
    </div>
  </div>
</header>

<main class="wrap">
  <div class="grid" id="grid"></div>
</main>

<script>
const DATA = {data_json};
let SHOW_NUMS = false;

function fmtNum(x, d=2) {{
  if (x === null || x === undefined || Number.isNaN(x)) return "—";
  return Number(x).toFixed(d);
}}

function renderKPIs(items) {{
  const total = items.length;
  const play = items.filter(x=>x.verdict==="PLAY").length;
  const hplay = items.filter(x=>x.verdict==="HIDDEN PLAY").length;
  const wa = items.filter(x=>x.verdict==="WATCH-A").length;
  const wb = items.filter(x=>x.verdict==="WATCH-B").length;
  const wc = items.filter(x=>x.verdict==="WATCH-C").length;
  const watch = items.filter(x=>x.verdict==="WATCH").length;
  const passc = items.filter(x=>x.verdict==="PASS").length;
  const tri = items.filter(x=>x.has_triangle).length;
  const pk = items.filter(x=>x.triangle_price_killed).length;
  const conf = items.filter(x=>x.tags && x.tags.CONFLICT_TAG==="CONFLICT: YES").length;

  document.getElementById("kpis").innerHTML = `
    <div class="kpi"><div class="muted">Toplam</div><b>${{total}}</b></div>
    <div class="kpi"><div class="muted">PLAY</div><b class="PLAY">${{play}}</b></div>
    <div class="kpi"><div class="muted">HIDDEN</div><b class="PLAY">${{hplay}}</b></div>
    <div class="kpi"><div class="muted">WATCH-A</div><b class="WATCH">${{wa}}</b></div>
    <div class="kpi"><div class="muted">WATCH-B</div><b class="WATCH">${{wb}}</b></div>
    <div class="kpi"><div class="muted">WATCH-C</div><b class="WATCH">${{wc}}</b></div>
    <div class="kpi"><div class="muted">WATCH</div><b class="WATCH">${{watch}}</b></div>
    <div class="kpi"><div class="muted">PASS</div><b class="PASS">${{passc}}</b></div>
    <div class="kpi"><div class="muted">Üçgen</div><b>${{tri}}</b></div>
    <div class="kpi"><div class="muted">Fiyat Öldü</div><b>${{pk}}</b></div>
    <div class="kpi"><div class="muted">Konflikt</div><b>${{conf}}</b></div>
  `;
}}

function chip(text) {{
  return `<div class="chip">${{text}}</div>`;
}}

function cardHTML(c) {{
  const badgeClass = (c.verdict==="PLAY"||c.verdict==="HIDDEN PLAY") ? "PLAY" : (c.verdict.startsWith("WATCH") ? "WATCH" : "PASS");
  const pick = c.pick || {{}};
  const tags = c.tags || {{}};

  const nums = (SHOW_NUMS)
    ? `<span class="nums">Odd ${{fmtNum(pick.odd,2)}} · Prob ${{fmtNum(pick.prob,3)}} · EV ${{fmtNum(pick.ev,2)}}</span>`
    : `<span class="nums muted">rakamlar kapalı</span>`;

  const densChip = chip(`📌 Yoğunluk <small>${{c.rows}} satır · ${{c.unique_markets}} market · ${{c.unique_characters}} karakter</small>`);
  const triChip = c.has_triangle ? chip(`🧩 Üçgen <small>${{c.triangle_types || ""}}</small>`) : "";
  const pkChip = c.triangle_price_killed ? chip(`💀 Fiyat Öldü <small>${{c.value_gate ? ("Gate: " + c.value_gate) : ""}}</small>`) : "";
  const confChip = (tags.CONFLICT_TAG==="CONFLICT: YES") ? chip(`⚠️ Konflikt <small>${{tags.CONFLICT_DETAIL || ""}}</small>`) : "";
  const relChip = chip(`🧠 Reliability <small>${{tags.RELIABILITY_TAG || ""}} · best: ${{tags.RELIABILITY_BEST_MARKET || ""}}</small>`);

  const tagChips = [
    tags.CORE_TAG, tags.SAMPLE_TAG, tags.EDGE_TAG, tags.CONSISTENCY_TAG, tags.ARCH_TAG, tags.PRICE_TAG, tags.STORY_TAG
  ].filter(Boolean).map(t => chip(`🏷️ <small>${{t}}</small>`)).join("");

  return `
    <div class="card">
      <div class="topline">
        <div>
          <div class="title">${{c.home}} – ${{c.away}}</div>
          <div class="headline">${{c.headline || ""}}</div>
          <div class="league">${{c.league}}</div>
        </div>
        <div class="badge ${{badgeClass}}">${{c.verdict}}</div>
      </div>

      <div class="chips">
        ${{densChip}}
        ${{triChip}}
        ${{pkChip}}
        ${{confChip}}
        ${{relChip}}
        <div class="chip">✅ Öneri <small>${{pick.market}} · ${{pick.profile}} · ${{pick.conf}} / ${{pick.am}}</small></div>
      </div>

      <div class="chips">
        ${{tagChips}}
      </div>

      <div class="pickbox">
        <div class="pickline">
          <b>${{pick.market}}</b>
          ${{nums}}
        </div>
      </div>

      <div class="narr">${{c.narrative}}</div>
      <div class="reason"><b>Mini Yorum:</b> ${{c.mini_comment}}</div>
      <div class="reason">Not: ${{c.reason}}</div>

      <details>
        <summary>Explain (neden bu karar?)</summary>
        <div class="explain">${{c.explain_html}}</div>
      </details>
    </div>
  `;
}}

function render(items) {{
  renderKPIs(items);

  const hidden = items.filter(x=>x.verdict==="HIDDEN PLAY");
  const wa = items.filter(x=>x.verdict==="WATCH-A");

  const topBlocks = [];
  if (hidden.length) {{
    topBlocks.push(`<div class="card" style="margin-bottom:12px;">
      <div class="topline">
        <div>
          <div class="title">🔥 HIDDEN PLAY (Yorumcu Oyunu)</div>
          <div class="league">Banko fiyatlanmış ama value kapısı açık. Tekli/düşük stake mantığı.</div>
        </div>
        <div class="badge PLAY">HIDDEN</div>
      </div>
      <div class="chips" style="margin-top:10px;">
        ${{hidden.slice(0,10).map(c=>`<div class="chip"><b>${{c.home}}–${{c.away}}</b> · <small>${{(c.pick||{{}}).market||""}}</small><br/><span class="muted">${{c.mini_comment||""}}</span></div>`).join("")}}
      </div>
    </div>`);
  }}

  if (wa.length) {{
    topBlocks.push(`<div class="card" style="margin-bottom:12px;">
      <div class="topline">
        <div>
          <div class="title">👀 WATCH-A (Karar Eşiği)</div>
          <div class="league">Hikâye net; fiyat izin veriyor. Teyit (kadro/tempo) ile PLAY’e dönebilir.</div>
        </div>
        <div class="badge WATCH">WATCH-A</div>
      </div>
      <div class="chips" style="margin-top:10px;">
        ${{wa.slice(0,12).map(c=>`<div class="chip"><b>${{c.home}}–${{c.away}}</b> · <small>${{(c.pick||{{}}).market||""}}</small><br/><span class="muted">${{c.mini_comment||""}}</span></div>`).join("")}}
      </div>
    </div>`);
  }}

  document.getElementById("grid").innerHTML = topBlocks.join("") + items.map(cardHTML).join("");
}}

function applyFilters() {{
  const q = (document.getElementById("q").value || "").trim().toLowerCase();
  const verdict = document.getElementById("verdict").value;
  const triangle = document.getElementById("triangle").value;
  const pk = document.getElementById("pricekilled").value;
  const terms = q ? q.split(/\\s+/).filter(Boolean) : [];

  const filtered = DATA.filter(c => {{
    if (verdict !== "ALL" && c.verdict !== verdict) return false;
    if (triangle === "YES" && !c.has_triangle) return false;
    if (triangle === "NO" && c.has_triangle) return false;
    if (pk === "YES" && !c.triangle_price_killed) return false;
    if (pk === "NO" && c.triangle_price_killed) return false;

    if (terms.length) {{
      const tags = c.tags || {{}};
      const tagText = Object.values(tags).join(" ");
      const hay = `${{c.home}} ${{c.away}} ${{c.league}} ${{c.triangle_types}} ${{(c.pick||{{}}).market||""}} ${{(c.pick||{{}}).profile||""}} ${{c.narrative}} ${{tagText}} ${{c.reason}} ${{c.headline}}`.toLowerCase();
      return terms.every(t => hay.includes(t));
    }}
    return true;
  }});

  render(filtered);
}}

["q","verdict","triangle","pricekilled"].forEach(id => {{
  document.getElementById(id).addEventListener("input", applyFilters);
  document.getElementById(id).addEventListener("change", applyFilters);
}});

document.getElementById("showNums").addEventListener("change", (e) => {{
  SHOW_NUMS = !!e.target.checked;
  applyFilters();
}});

render(DATA);
</script>
</body>
</html>
"""

out = "dashboard.html"
with open(out, "w", encoding="utf-8") as f:
    f.write(html)

print("✅ Upper (Clean) dashboard.html üretildi. İndirip tarayıcıda aç.")
files.download(out)