# -*- coding: utf-8 -*-
"""POOL-REPORT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ICllRcI10pOtSKCYvzPIX00CIO3Ecrs
"""

# ============================
# MATCH COMMENTARY REPORT (HTML) — FULL UPDATED (v3)
# SMART + COUPON BUILDER + FIXED KOMBO (NO DUPLICATE MARKETS)
#
# ✅ V3 CHANGES (requested):
# 1) Top 25 listeleri "Trust / Core" mantığıyla daha akıllı sıralıyor:
#    - En Yoğun Sinyal: Rows DESC → Core DESC → Conf/Auto → BestEV
#    - En Güçlü Çekirdek: Core DESC → Conf/Auto → Rows → BestEV
#    - En İyi Value: BestEV DESC → Core DESC → Rows → Conf/Auto
#    - (YENİ) Kalite Top25: Core DESC → (Conf+Auto yeşil bonus) → Rows → BestEV
# 2) Trust (CORE_SCORE) zaten vardı, listelerde tie-breaker olarak aktif kullanılıyor.
# 3) Best_EV hesaplaması NaN-safe yapıldı (tümü NaN ise patlamaz).
# 4) Komboda aynı marketin iki kez gelmesi hard-block (zaten vardı) + market-level unique korunuyor.
#
# ============================

import pandas as pd
import numpy as np
from collections import Counter
from html import escape
from pathlib import Path

# -----------------------------
# 0) LOAD (CSV / Excel) via Colab uploader
# -----------------------------
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]

if filename.lower().endswith((".xlsx", ".xls")):
    df = pd.read_excel(filename)
else:
    df = pd.read_csv(filename)

df = df.copy()

# -----------------------------
# 1) Numeric coercion
# -----------------------------
def to_num(s):
    return pd.to_numeric(s, errors="coerce")

NUM_COLS = [
    "MDL_rank","MDL_quantile","SIM_ANCHOR_STRENGTH","EFFECTIVE_N","_EN_PEN",
    "Odd","Prob","EV","Star_Rating","BestOfRank","GoldenScore_MDL","MDL_BOOST"
]
for c in NUM_COLS:
    if c in df.columns:
        df[c] = to_num(df[c])

if "Match_ID" not in df.columns:
    df["Match_ID"] = df.index.astype(str)

# -----------------------------
# 2) Helpers
# -----------------------------
def html_escape(x):
    return escape(str(x)) if x is not None else ""

def fmt(x, nd=2):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return ""
    try:
        return f"{float(x):.{nd}f}"
    except:
        return str(x)

def mode_or_blank(series):
    series = pd.Series(series).dropna()
    if len(series) == 0:
        return ""
    return series.mode().iloc[0]

def icon_mode(series):
    s = pd.Series(series).fillna("").astype(str)
    if len(s) == 0:
        return ""
    return Counter(s).most_common(1)[0][0]

def safe_str(x):
    return "" if x is None or (isinstance(x, float) and np.isnan(x)) else str(x)

def make_match_label(block):
    home = safe_str(block.iloc[0].get("HomeTeam","")).strip()
    away = safe_str(block.iloc[0].get("AwayTeam","")).strip()
    league = safe_str(block.iloc[0].get("League","")).strip()
    if home == "" and away == "":
        return f"(Unknown Match) ({league})" if league else "(Unknown Match)"
    return f"{home} – {away} ({league})" if league else f"{home} – {away}"

def anchor_to_strength(mean_anchor):
    if mean_anchor is None or (isinstance(mean_anchor, float) and np.isnan(mean_anchor)):
        return ("", "unknown")
    if mean_anchor >= 0.45: return ("🟩", "Çok Güçlü")
    if mean_anchor >= 0.40: return ("🟧", "Orta")
    if mean_anchor >= 0.35: return ("🟥", "Zayıf")
    return ("🟥", "Çok Zayıf")

def _nanmean(x):
    x = pd.to_numeric(pd.Series(x), errors="coerce")
    v = np.nanmean(x.values)
    return float(v) if np.isfinite(v) else np.nan

def _nanmax(x):
    x = pd.to_numeric(pd.Series(x), errors="coerce")
    if x.dropna().empty:
        return np.nan
    v = np.nanmax(x.values)
    return float(v) if np.isfinite(v) else np.nan

def _nanmin(x):
    x = pd.to_numeric(pd.Series(x), errors="coerce")
    if x.dropna().empty:
        return np.nan
    v = np.nanmin(x.values)
    return float(v) if np.isfinite(v) else np.nan

def robust_z(x, clip=2.5):
    s = pd.to_numeric(pd.Series(x), errors="coerce")
    med = np.nanmedian(s.values)
    mad = np.nanmedian(np.abs(s.values - med))
    if mad == 0 or np.isnan(mad):
        mu = np.nanmean(s.values)
        sd = np.nanstd(s.values)
        z = (s.values - mu) * 0.0 if (sd == 0 or np.isnan(sd)) else (s.values - mu) / sd
    else:
        z = 0.6745 * (s.values - med) / mad
    z = np.clip(z, -clip, clip)
    return pd.Series(z, index=s.index)

def priced_in_flag(prob, ev):
    if prob is None or ev is None: return False
    if (isinstance(prob,float) and np.isnan(prob)) or (isinstance(ev,float) and np.isnan(ev)): return False
    return (float(prob) >= 0.60 and float(ev) <= -2.0)

def icons_quality_bonus(conf_icon, auto_icon):
    # ✅ Kalite listesinde Conf/Auto'nun etkisini netleştiriyoruz (sıralamada tie-breaker)
    conf = (conf_icon or "").strip()
    auto = (auto_icon or "").strip()
    bonus = 0.0
    if conf == "🟢": bonus += 1.0
    elif conf == "🟡": bonus += 0.5
    if auto == "🟢": bonus += 1.0
    elif auto == "🟡": bonus += 0.5
    return bonus

# -----------------------------
# 3) Core / Trust
# -----------------------------
def summarize_core(block: pd.DataFrame):
    mdl_rank = mode_or_blank(block["MDL_rank"]) if "MDL_rank" in block.columns else ""
    qmin = _nanmin(block["MDL_quantile"]) if "MDL_quantile" in block.columns else np.nan
    qmax = _nanmax(block["MDL_quantile"]) if "MDL_quantile" in block.columns else np.nan
    anchor = _nanmean(block["SIM_ANCHOR_STRENGTH"]) if "SIM_ANCHOR_STRENGTH" in block.columns else np.nan
    effn   = _nanmean(block["EFFECTIVE_N"]) if "EFFECTIVE_N" in block.columns else np.nan
    enpen  = _nanmean(block["_EN_PEN"]) if "_EN_PEN" in block.columns else np.nan

    conf = icon_mode(block["CONF_ICON"]) if "CONF_ICON" in block.columns else ""
    automod = icon_mode(block["AUTOMOD_ICON"]) if "AUTOMOD_ICON" in block.columns else ""
    trap = icon_mode(block["TRAP_ICON"]) if "TRAP_ICON" in block.columns else ""
    danger = icon_mode(block["DANGER_ICON"]) if "DANGER_ICON" in block.columns else ""

    strength_dist = dict(Counter(block["STRENGTH_ICON"].fillna("").astype(str))) if "STRENGTH_ICON" in block.columns else {}
    cat_dist = dict(Counter(block["AnchorStrengthCategory"].fillna("").astype(str))) if "AnchorStrengthCategory" in block.columns else {}

    score = 0.0
    try:
        r = int(mdl_rank)
        score += 0.25 if r == 1 else (0.18 if r == 2 else 0.12)
    except:
        score += 0.14

    if not np.isnan(qmax): score += 0.22 * float(np.clip(qmax, 0, 1))
    if not np.isnan(anchor): score += 0.18 * float(np.clip((anchor - 0.30) / 0.20, 0, 1))
    if not np.isnan(effn): score += 0.22 * float(np.clip((effn - 15) / 35, 0, 1))

    if conf == "🟢": score += 0.07
    elif conf == "🟡": score += 0.04

    if automod == "🟢": score += 0.06
    elif automod == "🟡": score += 0.03

    penalty = 0.0
    if trap not in ("", "nan"): penalty += 0.10
    if danger not in ("", "nan"): penalty += 0.18

    def mix_pen(dist):
        if not dist: return 0.0
        total = sum(dist.values())
        if total <= 1: return 0.0
        top = max(dist.values())
        purity = top / total
        return float(np.clip((0.60 - purity) / 0.60, 0, 1)) * 0.06

    penalty += mix_pen(strength_dist)
    penalty += mix_pen(cat_dist)

    trust = float(np.clip(score - penalty, 0.0, 1.0))
    return {
        "MDL_rank": mdl_rank,
        "MDL_qmin": qmin,
        "MDL_qmax": qmax,
        "Anchor_mean": anchor,
        "EFFECTIVE_N_mean": effn,
        "_EN_PEN_mean": enpen,
        "CONF_ICON": conf,
        "AUTOMOD_ICON": automod,
        "TRAP_ICON": trap,
        "DANGER_ICON": danger,
        "STRENGTH_DIST": strength_dist,
        "CAT_DIST": cat_dist,
        "TRUST": trust,
        "TRUST_100": int(round(trust*100)),
    }

# -----------------------------
# 4) Market rows + consensus
# -----------------------------
def summarize_markets(block: pd.DataFrame):
    rows = []
    for _, r in block.iterrows():
        rows.append({
            "Market": safe_str(r.get("Seçim","")).strip(),
            "Odd": r.get("Odd", np.nan),
            "Prob": r.get("Prob", np.nan),
            "EV": r.get("EV", np.nan),
            "Character": safe_str(r.get("Karakter","")).strip(),
            "Star": r.get("Star_Rating", np.nan),
            "BestOfRank": r.get("BestOfRank", np.nan),
            "GoldenScore_MDL": r.get("GoldenScore_MDL", np.nan),
            "CONF_ICON": safe_str(r.get("CONF_ICON","")).strip(),
            "AUTOMOD_ICON": safe_str(r.get("AUTOMOD_ICON","")).strip(),
        })
    return rows

def market_consensus(block: pd.DataFrame):
    if "Seçim" not in block.columns: return {}
    total = len(block)
    if total == 0: return {}

    cons = {}
    for market, g in block.groupby("Seçim"):
        mk = safe_str(market).strip()
        if mk == "": continue
        share = len(g) / total
        if ("CONF_ICON" in g.columns and "AUTOMOD_ICON" in g.columns):
            green = int(((g["CONF_ICON"]=="🟢") & (g["AUTOMOD_ICON"]=="🟢")).sum())
        else:
            green = 0
        green_share = green / len(g) if len(g) else 0.0
        effn_mean = _nanmean(g["EFFECTIVE_N"]) if "EFFECTIVE_N" in g.columns else np.nan
        cons[mk] = {"share": share, "green_share": green_share, "effn_mean": effn_mean, "n": len(g)}

    effns = [v["effn_mean"] for v in cons.values() if not np.isnan(v["effn_mean"])]
    if len(effns):
        mn, mx = float(np.nanmin(effns)), float(np.nanmax(effns))
        for k in cons:
            e = cons[k]["effn_mean"]
            cons[k]["effn_norm"] = 0.5 if (np.isnan(e) or mx == mn) else float(np.clip((e - mn)/(mx-mn),0,1))
    else:
        for k in cons:
            cons[k]["effn_norm"] = 0.5

    for k, v in cons.items():
        v["cons_score"] = float(np.clip(0.55*v["share"] + 0.30*v["green_share"] + 0.15*v["effn_norm"], 0, 1))
    return cons

def score_markets_for_match(core, block):
    markets = summarize_markets(block)
    cons_map = market_consensus(block)
    ev_z = robust_z(pd.Series([m["EV"] for m in markets], dtype="float"), clip=2.5)

    scored = []
    for i, m in enumerate(markets):
        mk = safe_str(m.get("Market","")).strip()
        if mk == "":
            continue

        evz = float(ev_z.iloc[i]) if i in ev_z.index else 0.0
        ev_component = evz / 2.5  # ~ -1..1

        cons_score = cons_map.get(mk, {}).get("cons_score", 0.35)
        green_share = cons_map.get(mk, {}).get("green_share", 0.0)

        pen = 0.0
        if core["TRAP_ICON"] not in ("", "nan"): pen += 0.20
        if core["DANGER_ICON"] not in ("", "nan"): pen += 0.35
        if core["AUTOMOD_ICON"] == "🟡": pen += 0.05
        if core["AUTOMOD_ICON"] == "🔴": pen += 0.10
        if green_share < 0.25: pen += 0.06
        if priced_in_flag(m.get("Prob", np.nan), m.get("EV", np.nan)): pen += 0.12

        scale = (0.55 + 0.45*core["TRUST"]) * (0.60 + 0.40*cons_score)
        final = (ev_component * scale) - pen

        scored.append({
            **m,
            "EV_Z": evz,
            "Consensus": cons_score,
            "GreenShare": green_share,
            "FinalScore": final,
            "Penalty": pen
        })

    scored = sorted(
        scored,
        key=lambda x: (
            x.get("FinalScore", -999),
            float(x.get("EV", -999)) if pd.notna(x.get("EV")) else -999,
            float(x.get("Prob", -999)) if pd.notna(x.get("Prob")) else -999,
        ),
        reverse=True
    )
    return scored, cons_map

def pick_decision_smart(core, block):
    scored, cons = score_markets_for_match(core, block)
    if not scored:
        return None, ["Yeterli market verisi yok."], cons

    best = scored[0]
    reasons = []
    if core["CONF_ICON"] == "🟢": reasons.append("CONF 🟢 → model hikâyeyi destekliyor")
    if core["AUTOMOD_ICON"] == "🟢": reasons.append("AutoMod 🟢 → model mutabakatı güçlü")
    elif core["AUTOMOD_ICON"] == "🟡": reasons.append("AutoMod 🟡 → tam mutabakat yok (dalga payı)")

    if pd.notna(core["EFFECTIVE_N_mean"]) and core["EFFECTIVE_N_mean"] >= 30:
        reasons.append(f"EFFECTIVE_N {fmt(core['EFFECTIVE_N_mean'],2)} → örneklem güçlü")
    if pd.notna(core["Anchor_mean"]):
        reasons.append(f"Anchor {fmt(core['Anchor_mean'],3)} → yapısal omurga seviyesi")

    reasons.append(f"Market konsensüsü: {fmt(best['Consensus'],2)}")
    reasons.append(f"FinalScore: {fmt(best['FinalScore'],3)} (EV + güven + konsensüs)")

    if priced_in_flag(best.get("Prob", np.nan), best.get("EV", np.nan)):
        reasons.append("Not: Prob yüksek ama EV negatif → market fiyatlanmış olabilir (priced-in).")
    if core["TRAP_ICON"] not in ("", "nan") or core["DANGER_ICON"] not in ("", "nan"):
        reasons.append("Uyarı: TRAP/DANGER etiketi var → temkinli.")

    return best, reasons, cons

def story_triangle(markets_scored):
    mset = set([safe_str(m.get("Market","")).strip() for m in markets_scored])
    story = []
    if any((x.strip() == "MS 1") or ("MS1" in x.replace(" ", "")) for x in mset):
        story.append("Favori taraf baskın görünüyor (MS1).")
    if any(("Üst" in x) or ("Over" in x) for x in mset):
        story.append("Gol üretme potansiyeli var (Üst).")
    if any(("KG Var" in x) or ("BTTS" in x) for x in mset):
        story.append("İki tarafın da skora dokunma ihtimali masada (KG Var).")
    if not story:
        story.append("Market çeşitliliği düşük → anlatıyı daha çok çekirdek sinyal belirliyor.")
    return " ".join(story)

# -----------------------------
# 5) Build match-level best table + cache
# -----------------------------
def build_match_best_table(df):
    rows = []
    match_cache = {}

    for mid, block in df.groupby("Match_ID", sort=False):
        core = summarize_core(block)
        label = make_match_label(block)
        scored, cons_map = score_markets_for_match(core, block)
        best = scored[0] if scored else None

        # ✅ NaN-safe Best_EV
        ev_vals = [m.get("EV", np.nan) for m in scored] if scored else []
        ev_vals = pd.to_numeric(pd.Series(ev_vals), errors="coerce")
        best_ev = float(np.nanmax(ev_vals.values)) if (len(ev_vals) and ev_vals.notna().any()) else np.nan

        match_cache[mid] = {
            "label": label,
            "core": core,
            "scored": scored,
            "cons": cons_map,
            "rows": len(block)
        }

        rows.append({
            "Match_ID": mid,
            "Match_Label": label,
            "Rows": len(block),
            "CORE_SCORE": core["TRUST_100"],              # Trust(0-100)
            "CONF_ICON": core["CONF_ICON"],
            "AUTOMOD_ICON": core["AUTOMOD_ICON"],
            "ICONS_BONUS": icons_quality_bonus(core["CONF_ICON"], core["AUTOMOD_ICON"]),  # ✅ kalite sıralama
            "Best_EV": best_ev,

            "Decision_Market": "" if best is None else best.get("Market",""),
            "Decision_Odd": np.nan if best is None else best.get("Odd", np.nan),
            "Decision_Prob": np.nan if best is None else best.get("Prob", np.nan),
            "Decision_EV": np.nan if best is None else best.get("EV", np.nan),
            "Decision_FinalScore": np.nan if best is None else best.get("FinalScore", np.nan),
        })

    return pd.DataFrame(rows), match_cache

# -----------------------------
# 6) Coupon Builder (Banko / Surprise / System / Kombo) - FULL FIXED
# -----------------------------
def build_coupons(best_df, match_cache,
                  banko_n=5, surpriz_n=4, system_n=8, kombo_n=6):

    def unique_by_match(picks):
        seen = set()
        out = []
        for p in picks:
            if p["Match_ID"] in seen:
                continue
            seen.add(p["Match_ID"])
            out.append(p)
        return out

    base = []
    for _, r in best_df.iterrows():
        base.append({
            "Match_ID": r["Match_ID"],
            "Match_Label": r["Match_Label"],
            "Pick": r["Decision_Market"],
            "Odd": r["Decision_Odd"],
            "Prob": r["Decision_Prob"],
            "EV": r["Decision_EV"],
            "FinalScore": r["Decision_FinalScore"],
            "Trust": r["CORE_SCORE"],
            "Conf": r["CONF_ICON"],
            "Auto": r["AUTOMOD_ICON"],
            "Rows": r["Rows"]
        })

    # --- BANKO
    banko = [p for p in base
             if safe_str(p["Pick"]).strip() != ""
             and pd.notna(p["Prob"]) and float(p["Prob"]) >= 0.62
             and pd.notna(p["Odd"]) and float(p["Odd"]) <= 1.65
             and pd.notna(p["FinalScore"]) and float(p["FinalScore"]) > -0.02
             and int(p["Trust"]) >= 70
             and p["Conf"] in ("🟢","🟡")]
    banko = sorted(banko, key=lambda x: (x["Trust"], float(x["Prob"]), -float(x["Odd"])), reverse=True)
    banko = unique_by_match(banko)[:banko_n]

    # --- SURPRIZ
    surpriz = [p for p in base
               if safe_str(p["Pick"]).strip() != ""
               and pd.notna(p["Odd"]) and float(p["Odd"]) >= 2.10
               and pd.notna(p["FinalScore"]) and float(p["FinalScore"]) > 0.00
               and int(p["Trust"]) >= 55]
    surpriz = sorted(surpriz, key=lambda x: (float(x["FinalScore"]), float(x["Odd"])), reverse=True)
    surpriz = unique_by_match(surpriz)[:surpriz_n]

    # --- SYSTEM
    system = [p for p in base
              if safe_str(p["Pick"]).strip() != ""
              and pd.notna(p["Odd"]) and 1.70 <= float(p["Odd"]) <= 3.50
              and pd.notna(p["FinalScore"]) and float(p["FinalScore"]) > 0.00
              and int(p["Trust"]) >= 60]
    system = sorted(system, key=lambda x: (float(x["FinalScore"]), x["Trust"]), reverse=True)
    system = unique_by_match(system)[:system_n]

    # --- KOMBO (FIXED)
    combo_candidates = []

    def synergy(a: str, b: str) -> float:
        A, B = (a or "").strip(), (b or "").strip()
        pos = {
            ("MS 1","2.5 Üst"): 0.10, ("2.5 Üst","MS 1"): 0.10,
            ("MS 1","KG Var"):  0.10, ("KG Var","MS 1"):  0.10,
            ("MS 2","2.5 Üst"): 0.10, ("2.5 Üst","MS 2"): 0.10,
            ("MS 2","KG Var"):  0.10, ("KG Var","MS 2"):  0.10,
            ("MSX","2.5 Alt"):  0.12, ("2.5 Alt","MSX"):  0.12,
            ("MSX","KG Yok"):   0.12, ("KG Yok","MSX"):   0.12,
        }
        neg = {
            ("MS 1","2.5 Alt"): -0.10, ("2.5 Alt","MS 1"): -0.10,
            ("MS 1","KG Yok"):  -0.10, ("KG Yok","MS 1"):  -0.10,
            ("MS 2","2.5 Alt"): -0.08, ("2.5 Alt","MS 2"): -0.08,
            ("MS 2","KG Yok"):  -0.08, ("KG Yok","MS 2"):  -0.08,
        }
        return pos.get((A,B), 0.0) + neg.get((A,B), 0.0)

    def ms1_low_odd_penalty(market: str, odd: float) -> float:
        if (market or "").strip() == "MS 1" and pd.notna(odd) and float(odd) <= 1.30:
            return 0.10
        return 0.0

    def market_type(name: str) -> str:
        n = (name or "").strip()
        if n in ("MS 1","MS 2","MSX"): return "MS"
        if "Alt" in n or "Üst" in n or "Over" in n or "Under" in n: return "OU"
        if "KG" in n or "BTTS" in n: return "BTTS"
        return "OTHER"

    # ✅ İstersen False yap: OU+OU veya BTTS+BTTS gibi ikilileri engeller
    ALLOW_SAME_TYPE = True

    for mid, info in match_cache.items():
        scored = info["scored"]
        core = info["core"]
        if not scored:
            continue

        trust100 = int(round(core["TRUST"]*100))
        if trust100 < 60:
            continue

        # (A) Market-level unique (same market appears many rows → keep best FinalScore row)
        best_by_market = {}
        for m in scored:
            mk = safe_str(m.get("Market","")).strip()
            if mk == "":
                continue
            cur = best_by_market.get(mk)
            if (cur is None) or (float(m.get("FinalScore",-999)) > float(cur.get("FinalScore",-999))):
                best_by_market[mk] = m

        market_list = list(best_by_market.values())
        if len(market_list) < 2:
            continue

        # (B) Top-K markets (not rows)
        K = 5
        top = sorted(market_list, key=lambda x: (x.get("FinalScore",-999), x.get("EV",-999)), reverse=True)[:K]
        if len(top) < 2:
            continue

        best_for_match = None

        # (C) all distinct pairs
        for i in range(len(top)):
            for j in range(i+1, len(top)):
                a, b = top[i], top[j]
                ma, mb = safe_str(a.get("Market","")).strip(), safe_str(b.get("Market","")).strip()

                # ✅ hard rule: no same market twice
                if ma == mb:
                    continue

                if (not ALLOW_SAME_TYPE) and (market_type(ma) == market_type(mb)):
                    continue

                oa, ob = a.get("Odd", np.nan), b.get("Odd", np.nan)
                pa, pb = a.get("Prob", np.nan), b.get("Prob", np.nan)
                ea, eb = a.get("EV", np.nan), b.get("EV", np.nan)

                if pd.isna(oa) or pd.isna(ob):
                    continue

                combo_odd = float(oa) * float(ob)
                if combo_odd < 2.10:
                    continue

                if priced_in_flag(pa, ea) and priced_in_flag(pb, eb):
                    continue

                fsa = float(a.get("FinalScore",-1))
                fsb = float(b.get("FinalScore",-1))
                if max(fsa, fsb) <= 0.00:
                    continue

                combo_prob = (float(pa) if pd.notna(pa) else 0.5) * (float(pb) if pd.notna(pb) else 0.5)

                syn = synergy(ma, mb)
                pen = ms1_low_odd_penalty(ma, oa) + ms1_low_odd_penalty(mb, ob)

                cons_min = min(float(a.get("Consensus",0.35)), float(b.get("Consensus",0.35)))
                combo_score = ((fsa + fsb)/2.0) + 0.15*core["TRUST"] + syn + 0.08*cons_min - pen

                cand = {
                    "Match_ID": mid,
                    "Match_Label": info["label"],
                    "LegA": ma, "OddA": oa, "ProbA": pa, "EVA": ea,
                    "LegB": mb, "OddB": ob, "ProbB": pb, "EVB": eb,
                    "Combo_Odd": combo_odd,
                    "Combo_Prob": combo_prob,
                    "Combo_Score": combo_score,
                    "Trust": trust100,
                    "Conf": core["CONF_ICON"],
                    "Auto": core["AUTOMOD_ICON"],
                }

                if (best_for_match is None) or (cand["Combo_Score"] > best_for_match["Combo_Score"]):
                    best_for_match = cand

        if best_for_match is not None:
            combo_candidates.append(best_for_match)

    combo_candidates = sorted(combo_candidates, key=lambda x: (x["Combo_Score"], x["Combo_Odd"]), reverse=True)
    combo = combo_candidates[:kombo_n]

    return {
        "banko": banko,
        "surpriz": surpriz,
        "system": system,
        "combo": combo,
    }

# -----------------------------
# 7) HTML builders
# -----------------------------
def coupon_table(title, picks, kind="single"):
    if kind == "single":
        if not picks:
            body = "<div class='muted'>Uygun seçim bulunamadı (eşikler çok sıkı olabilir).</div>"
        else:
            rows = []
            total_odd = 1.0
            for p in picks:
                if pd.notna(p["Odd"]):
                    total_odd *= float(p["Odd"])
                rows.append(f"""
                  <tr>
                    <td><a href="#{html_escape(p['Match_ID'])}">{html_escape(p['Match_Label'])}</a></td>
                    <td><b>{html_escape(p['Pick'])}</b></td>
                    <td>{fmt(p['Odd'],2)}</td>
                    <td>{fmt(p['Prob'],3)}</td>
                    <td>{fmt(p['EV'],2)}</td>
                    <td>{fmt(p['FinalScore'],3)}</td>
                    <td>{int(p['Trust'])}</td>
                    <td>{html_escape(p['Conf'])} / {html_escape(p['Auto'])}</td>
                  </tr>
                """)
            body = f"""
            <div class="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>Maç</th><th>Seçim</th><th>Oran</th><th>Prob</th><th>EV</th><th>Final</th><th>Trust</th><th>Conf/Auto</th>
                  </tr>
                </thead>
                <tbody>{''.join(rows)}</tbody>
              </table>
            </div>
            <div class="muted" style="margin-top:8px;">Kupon toplam oran (çarpım): <b>{fmt(total_odd,2)}</b></div>
            """
        return f"""
        <div class="card">
          <div class="card-title">{html_escape(title)}</div>
          {body}
        </div>
        """
    else:
        if not picks:
            body = "<div class='muted'>Uygun kombo bulunamadı.</div>"
        else:
            rows = []
            for c in picks:
                rows.append(f"""
                <tr>
                  <td><a href="#{html_escape(c['Match_ID'])}">{html_escape(c['Match_Label'])}</a></td>
                  <td><b>{html_escape(c['LegA'])}</b> @ {fmt(c['OddA'],2)} + <b>{html_escape(c['LegB'])}</b> @ {fmt(c['OddB'],2)}</td>
                  <td><b>{fmt(c['Combo_Odd'],2)}</b></td>
                  <td>{fmt(c['Combo_Prob'],3)}</td>
                  <td>{fmt(c['Combo_Score'],3)}</td>
                  <td>{c['Trust']}</td>
                  <td>{html_escape(c['Conf'])} / {html_escape(c['Auto'])}</td>
                </tr>
                """)
            body = f"""
            <div class="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>Maç</th><th>Kombo</th><th>Toplam Oran</th><th>Combo Prob (≈)</th><th>Combo Score</th><th>Trust</th><th>Conf/Auto</th>
                  </tr>
                </thead>
                <tbody>{''.join(rows)}</tbody>
              </table>
            </div>
            """
        return f"""
        <div class="card">
          <div class="card-title">{html_escape(title)}</div>
          {body}
          <div class="muted" style="margin-top:8px;">
            Not: Kombo Prob yaklaşık hesap (bağımsız varsayım). Sıralama sinyali olarak kullanılır.
          </div>
        </div>
        """

def render_match_section(match_id, block):
    label = make_match_label(block)
    core = summarize_core(block)
    scored, _ = score_markets_for_match(core, block)
    best, reasons, _ = pick_decision_smart(core, block)
    tri = story_triangle(scored)

    trap_ok = (core["TRAP_ICON"] in ("", "nan") and core["DANGER_ICON"] in ("", "nan"))
    anchor_icon, anchor_label = anchor_to_strength(core["Anchor_mean"])

    if core["CONF_ICON"] == "🟢" and core["AUTOMOD_ICON"] == "🟢" and str(core["MDL_rank"]) == "1" and trap_ok:
        readout = "👉 Okuma: Model + AutoMod aynı anda yeşil, rank 1, etiket temiz. Çekirdek olarak sağlam."
    else:
        readout = "👉 Okuma: Çekirdek güçlü olabilir ama tam konfor yok (dalga payı)."

    mt_rows = []
    for m in scored:
        pin = "priced-in" if priced_in_flag(m.get("Prob", np.nan), m.get("EV", np.nan)) else ""
        mt_rows.append(f"""
          <tr>
            <td>{html_escape(m.get('Market',''))}</td>
            <td>{fmt(m.get('Odd',np.nan),2)}</td>
            <td>{fmt(m.get('Prob',np.nan),3)}</td>
            <td>{fmt(m.get('EV',np.nan),2)}</td>
            <td>{html_escape(m.get('Character',''))}</td>
            <td>{fmt(m.get('Star',np.nan),0)}</td>
            <td>{fmt(m.get('Consensus',np.nan),2)}</td>
            <td>{fmt(m.get('FinalScore',np.nan),3)} <span class="muted">{html_escape(pin)}</span></td>
          </tr>
        """)

    decision_html = ""
    if best is not None:
        decision_html = f"""
        <div class="decision">
          <div class="decision-title">✅ Tek Seçim (Decision)</div>
          <div class="decision-pick"><b>{html_escape(best.get('Market',''))}</b> @ <b>{fmt(best.get('Odd',np.nan),2)}</b></div>
          <div class="decision-meta">Prob: {fmt(best.get('Prob',np.nan),3)} | EV: {fmt(best.get('EV',np.nan),2)} | Final: {fmt(best.get('FinalScore',np.nan),3)}</div>
          <ul class="reasons">
            {''.join([f"<li>{html_escape(r)}</li>" for r in reasons])}
          </ul>
        </div>
        """

    core_html = f"""
    <div class="core-grid">
      <div class="core-item"><span class="k">MDL_rank</span><span class="v">{html_escape(core['MDL_rank'])}</span></div>
      <div class="core-item"><span class="k">MDL_quantile</span><span class="v">{fmt(core['MDL_qmin'],3)} – {fmt(core['MDL_qmax'],3)}</span></div>
      <div class="core-item"><span class="k">SIM_ANCHOR_STRENGTH</span><span class="v">{fmt(core['Anchor_mean'],3)} {anchor_icon} <span class="muted">({anchor_label})</span></span></div>
      <div class="core-item"><span class="k">EFFECTIVE_N</span><span class="v">{fmt(core['EFFECTIVE_N_mean'],2)}</span></div>
      <div class="core-item"><span class="k">_EN_PEN</span><span class="v">{fmt(core['_EN_PEN_mean'],2)}</span></div>
      <div class="core-item"><span class="k">CONF_ICON</span><span class="v">{html_escape(core['CONF_ICON'])}</span></div>
      <div class="core-item"><span class="k">AUTOMOD_ICON</span><span class="v">{html_escape(core['AUTOMOD_ICON'])}</span></div>
      <div class="core-item"><span class="k">TRAP/DANGER</span><span class="v">{html_escape(core['TRAP_ICON'])} {html_escape(core['DANGER_ICON'])} <span class="muted">{'✓ temiz' if trap_ok else '⚠ işaret var'}</span></span></div>
      <div class="core-item"><span class="k">TRUST</span><span class="v"><b>{core['TRUST_100']}</b>/100</span></div>
    </div>
    """

    return f"""
    <section id="{html_escape(match_id)}" class="match">
      <div class="match-header">
        <div class="match-title">{html_escape(label)}</div>
        <div class="match-sub">Match_ID: <code>{html_escape(match_id)}</code> • Satır sayısı: <b>{len(block)}</b></div>
      </div>

      <h3>1) Maçın çekirdeği (yapısal güven)</h3>
      {core_html}
      <div class="readout">{html_escape(readout)}</div>

      <h3>2) Bu maçta hangi tahminler var? (market çeşitliliği)</h3>
      <div class="story"><b>Senaryo:</b> {html_escape(tri)}</div>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Market</th><th>Odd</th><th>Prob</th><th>EV</th><th>Karakter</th><th>Star</th><th>Consensus</th><th>FinalScore</th>
            </tr>
          </thead>
          <tbody>
            {''.join(mt_rows)}
          </tbody>
        </table>
      </div>

      <h3>3) Neyi seçerdim? (ikna + fiyat + konsensüs)</h3>
      {decision_html}
    </section>
    """

def build_index_tables(best_df, top_n=25):
    def table_html(title, dfpart):
        rows = []
        for _, r in dfpart.iterrows():
            rows.append(f"""
              <tr>
                <td><a href="#{html_escape(r['Match_ID'])}">{html_escape(r['Match_Label'])}</a></td>
                <td>{int(r['Rows'])}</td>
                <td><b>{int(r['CORE_SCORE'])}</b></td>
                <td>{html_escape(r['CONF_ICON'])}</td>
                <td>{html_escape(r['AUTOMOD_ICON'])}</td>
                <td>{fmt(r['Best_EV'],2)}</td>
                <td>{html_escape(r['Decision_Market'])}</td>
                <td>{fmt(r['Decision_Odd'],2)}</td>
              </tr>
            """)
        return f"""
        <div class="card">
          <div class="card-title">{html_escape(title)}</div>
          <div class="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Maç</th><th>Satır</th><th>Trust/Core</th><th>Conf</th><th>Auto</th><th>Best EV</th><th>Decision</th><th>Odd</th>
                </tr>
              </thead>
              <tbody>{''.join(rows)}</tbody>
            </table>
          </div>
        </div>
        """

    # ✅ Sıralamalar: Trust tie-breaker aktif
    by_signal = best_df.sort_values(
        ["Rows","CORE_SCORE","ICONS_BONUS","Best_EV"],
        ascending=[False,False,False,False]
    ).head(top_n)

    by_core = best_df.sort_values(
        ["CORE_SCORE","ICONS_BONUS","Rows","Best_EV"],
        ascending=[False,False,False,False]
    ).head(top_n)

    by_value = best_df.sort_values(
        ["Best_EV","CORE_SCORE","Rows","ICONS_BONUS"],
        ascending=[False,False,False,False]
    ).head(top_n)

    # ✅ Yeni: Kalite Top25 (Trust + Icons öncelik)
    by_quality = best_df.sort_values(
        ["CORE_SCORE","ICONS_BONUS","Rows","Best_EV"],
        ascending=[False,False,False,False]
    ).head(top_n)

    return (
      table_html(f"Top {top_n} — En Yoğun Sinyal (Rows) + Trust Tie-break", by_signal) +
      table_html(f"Top {top_n} — En Güçlü Çekirdek (Trust/Core) + Icons Tie-break", by_core) +
      table_html(f"Top {top_n} — En İyi Value (Best EV) + Trust Tie-break", by_value) +
      table_html(f"Top {top_n} — Kalite Listesi (Trust + Conf/Auto ağırlıklı)", by_quality)
    )

CSS = """
:root { --bg:#0b0f17; --card:#121a2a; --muted:#9aa4b2; --text:#e6edf3; --line:#243044; --accent:#7dd3fc; }
*{box-sizing:border-box}
body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial;background:var(--bg);color:var(--text);line-height:1.45}
.container{max-width:1100px;margin:0 auto;padding:28px}
h1{margin:0 0 6px 0;font-size:28px}
.subtitle{color:var(--muted);margin-bottom:18px}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:14px 14px 6px;margin:14px 0}
.card-title{font-weight:900;margin:0 0 10px 0}
.table-wrap{overflow:auto;border-radius:12px;border:1px solid var(--line)}
table{width:100%;border-collapse:collapse;min-width:860px}
th,td{padding:10px 10px;border-bottom:1px solid var(--line);font-size:13px;vertical-align:top}
th{color:#c9d1d9;text-align:left;background:rgba(255,255,255,0.03);position:sticky;top:0}
a{color:var(--accent);text-decoration:none}
a:hover{text-decoration:underline}
.match{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:16px;margin:16px 0}
.match-header{display:flex;flex-direction:column;gap:4px;margin-bottom:10px}
.match-title{font-size:18px;font-weight:950}
.match-sub{color:var(--muted);font-size:13px}
.muted{color:var(--muted)}
code{background:rgba(255,255,255,0.06);padding:2px 6px;border-radius:8px}
.core-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:10px 0 6px}
.core-item{background:rgba(255,255,255,0.03);border:1px solid var(--line);border-radius:12px;padding:10px}
.core-item .k{display:block;color:var(--muted);font-size:12px}
.core-item .v{display:block;font-size:14px;font-weight:650;margin-top:2px}
.readout{margin:10px 0 0 0;color:#dbeafe}
.story{margin:6px 0 10px 0;color:#e0f2fe}
.decision{margin:10px 0 0 0;border:1px solid rgba(125,211,252,0.35);background:rgba(125,211,252,0.06);border-radius:14px;padding:12px}
.decision-title{font-weight:950;margin-bottom:6px}
.decision-pick{font-size:16px}
.decision-meta{color:var(--muted);font-size:13px;margin-top:2px}
.reasons{margin:8px 0 0 18px;color:#e5e7eb}
.footer{color:var(--muted);font-size:12px;margin-top:18px}
@media (max-width:900px){ .core-grid{grid-template-columns:1fr} table{min-width:920px} }
"""

def build_html_report(df, best_df, match_cache, top_n=25, out_path="match_report.html"):
    index_tables = build_index_tables(best_df, top_n=top_n)

    coupons = build_coupons(best_df, match_cache,
                            banko_n=5, surpriz_n=4, system_n=8, kombo_n=6)

    coupon_html = (
        coupon_table("🎫 Banko Kupon (yüksek güven, düşük-orta oran)", coupons["banko"], kind="single") +
        coupon_table("🎲 Sürpriz Kupon (yüksek oran, kontrollü risk)", coupons["surpriz"], kind="single") +
        coupon_table("🧩 Sistem Kupon Adayları (çok maçlı havuz)", coupons["system"], kind="single") +
        coupon_table("🔗 Kombo Kupon (akıllı 2’li: Top-K market + uyum + ceza) — DUP FIXED", coupons["combo"], kind="combo")
    )

    sections = []
    for mid, block in df.groupby("Match_ID", sort=False):
        sections.append(render_match_section(mid, block))

    html = f"""
<!doctype html>
<html lang="tr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Match Commentary Report</title>
  <style>{CSS}</style>
</head>
<body>
  <div class="container">
    <h1>Match Commentary Report</h1>
    <div class="subtitle">
      Üstte kupon önerileri + Top listeler + aşağıda maç yorumları. • TopN={top_n} • Toplam maç={best_df.shape[0]} • Toplam satır={df.shape[0]}
    </div>

    <div class="card">
      <div class="card-title">Kupon Önerileri (Otomatik)</div>
      <div class="subtitle">
        Mantık: FinalScore (EV + Trust + Konsensüs) ile seçer.
        Kombo: sabit pattern değil; Top-K marketten en iyi ikiliyi bulur.
        (Aynı market iki kez seçilmez.)
      </div>
    </div>

    {coupon_html}

    {index_tables}

    <div class="card">
      <div class="card-title">Tüm Maç Yorumları</div>
      <div class="subtitle">Üst tablodan maça tıkla → direkt ilgili bölüme zıpla.</div>
    </div>

    {''.join(sections)}

    <div class="footer">
      Üretim: Colab HTML Export • Not: “Sistem kupon” için pratik: 3/8 veya 4/8 gibi sistemler.
    </div>
  </div>
</body>
</html>
"""
    Path(out_path).write_text(html, encoding="utf-8")
    return out_path

# -----------------------------
# 8) RUN
# -----------------------------
best_df, match_cache = build_match_best_table(df)
out_file = build_html_report(df, best_df, match_cache, top_n=25, out_path="match_report.html")
print("OK ->", out_file)

files.download("match_report.html")